import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import styles from "./index.module.css";

export default function Home() {
  const hello = api.get.hello.useQuery({ text: "from ecommerce-app" });

  const page_no = 10;
  const all_categories = api.get.getCategories.useQuery({ page_no: page_no});

  let all_category_names = "";
  if(all_categories.data){
    for(const category of all_categories.data) {
      all_category_names += category.name + ", ";
    }
  }

  const user_email = "mangesh@gatech.edu";
  const user_password = "password123"; 
  const wrong_password = "123password";
  // api.post.createUser.useMutation().mutate({ email: user_email, name: "Mangesh",  password: user_password});
  // api.post.updateUserCategories.useMutation().mutate({email: user_email, category: "Electronics"});

  const user_info = api.get.getUser.useQuery({ email: user_email });
  let user_name = "";
  let user_category = "";
  if(user_info.data && user_info.data.name){
    user_name = user_info.data.name;
    user_category = user_info.data.selected_categories || "";
  }

  const match_password = api.get.matchPassword.useQuery({ email: user_email, password: user_password });
  const match_wrong_password = api.get.matchPassword.useQuery({ email: user_email, password: wrong_password });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          {/* <h1 className={styles.title}>
            Create <span className={styles.pinkSpan}>T3</span> App
          </h1>
          <div className={styles.cardRow}>
            <Link
              className={styles.card}
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>First Steps →</h3>
              <div className={styles.cardText}>
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className={styles.card}
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>Documentation →</h3>
              <div className={styles.cardText}>
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div> */}
          <p className={styles.showcaseText}>
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>

          <p className={styles.showcaseText}>
            {"getCategories API. Page No = " + page_no + " :"}
          </p>
          <p className={styles.showcaseText}>
            {all_category_names ? all_category_names : "Loading tRPC query..."}
          </p>

          <p className={styles.showcaseText}>
            {"getUser API. Email = " + user_email + " :"}
          </p>
          <p className={styles.showcaseText}>
            {(user_name ? user_name : "Loading tRPC query...") + ", "}
            {user_category ? user_category : "Loading tRPC query..."}
          </p>

          <p className={styles.showcaseText}>
            {"matchPassword API. Email = " + user_email + " and Password = " + user_password + " :"}
          </p>
          <p className={styles.showcaseText}>
            {String(match_password.data) ? "Success = " + String(match_password.data) : "Loading tRPC query..."}
          </p>

          <p className={styles.showcaseText}>
            {"matchPassword API. Email = " + user_email + " and Password = " + wrong_password + " :"}
          </p>
          <p className={styles.showcaseText}>
            {String(match_wrong_password.data) ? "Success = " + String(match_wrong_password.data) : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
}
